# 1.基本概念

+ 标量
单个的数字。*没有参数的函数*
+ 向量
一维线性表。*拥有一个参数的函数*
+ 矩阵
二维表格。*拥有两个参数的函数*
+ 高阶张量
多维表。 *拥有两个以上参数的函数*


# 2.矩阵（向量）的点运算（乘法运算）
设矩阵
$ A =\begin{bmatrix}
a_{1,1} & a_{1,2} & \cdots & a_{1,q} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m,1} & a_{m,2} & \cdots & a_{m,q}
 \end{bmatrix}
$
,
$ B =\begin{bmatrix}
b_{1,1} & b_{1,2} & \cdots & b_{1,n} \\
\vdots & \vdots & \ddots & \vdots \\
b_{q,1} & b_{q,2} & \cdots & b_{q,n}
 \end{bmatrix}
$

向量$x=\begin{bmatrix} x_1 & x_2 & \cdots & x_n \end{bmatrix}^T$，  $y=\begin{bmatrix} y_1 & y_2 & \cdots & y_n \end{bmatrix}^T$

+ 向量内积
$<x,y>=\sum_{i=1}^n x_i*y_i$ 。 <br>前提：两向量具有相同的长度
+ 范数
欧式空间向量的范数为该向量的长度，即x的范数$\lVert n\rVert _2 = \sqrt {<x,x>}$
+ 向量外积
$S = outer（x,y）$，其中$s_{i,j}=x_i*y_j$
+ 矩阵向量运算
$z=Ax$是一个向量，其中$z_i=\sum_{j=1}^na_{i,j}*x_j =<A_i, x>$，即矩阵A的每一行和向量x进行内积，z的长度为A的行数。
<br>前提：向量的长度和矩阵的列数相同。
+ 矩阵-矩阵运算
$C = A \times B$，其中$c_{i,j}=\sum_{\mathscr{k}=1}^qA_{i,\mathscr{k}}*B_{\mathscr{k},j}$，即元素$C_{i,j}$是A的第i行和B的第j列的内积。C的维度为m * n。
<br>前提：A矩阵的列数和B矩阵的行数相同。

# 3.numpy中的矩阵和向量
## 3.1 创建向量和矩阵。
<br>使用列表及array函数创建向量和矩阵。<br>
dtype可选，默认为指定数据类型。

```python
import numpy as np
v1 = np.array([1., 2., 3.], dtype = float) 
v2 = np.array([2, 1, 0])   #数据类型为整形 
M = np.array([[1.,2., 3.],[3.,4.,6]])  # 2行3列
Mx = np.array([[5.,6.,7.],[7.,8.,9.]])
N = np.array([[5.,6.,7.],[7.,8.,9.],[9.,10.,11.]])  #3行3列
v2[0] = 0.5  #变为[0,1,0]
```
注意，如果矩阵或向量的数据类型为整形，若再为其赋值浮点型数据，则会取整截断。
## 3.2 向量和矩阵的区别

```python
#向量,没有行和列的概念，4个元素
v = np.array([1.,2.,3.,4.]) 
#行矩阵，4个元素，1行4列。注意括号
M1 = np.array([[1.,2.,3.,4.]])
#列矩阵，4个元素,4行1列。
M2 = np.array([[1.],[2.],[3.],[4.]])
```

# 4.线性代数运算
## 4.1 向量或矩阵与标量的运算
 
```python
#标量乘，每个元素乘上该标量
v1 / 2   
2 * v1
6 * M

#线性组合
2 * v1 + 3 * v2
```
## 4.2 向量或矩阵的元素运算

```python

#元素间运算,对应位置元素间的运算
v1 * v2   #array([2,2,0])
v1 / v2
v1 - v2
v1 + v2
M + Mx
M - Mx
M * Mx
M / Mx

#作用与元素的函数
np.cos(v1)   #array([0.54,-0.416,-0.9899])

```
## 4.3 线性代数运算

```python
#向量内积，三种形式一致
v3 = np.inner(v1,v2)
v3 = np.dot（v1,v2）
v3 = v1 @ v2

#矩阵-向量，注意维度兼容性
v4 = np.dot(M, v1)
v4 = M @ v1

#矩阵-矩阵,注意维度兼容性
P = np.dot(M,N) #M 2行3列，N 3行3列，则矩阵p的维度为？
P = M @ N

```

# 5.numpy数组的属性
数组有三个属性

| 名称 | 说明   |
| : -------- : | :-------|
| shape | 描述了数组每个方向上的维度。可以使用shape属性访问,它是一个元组，其长度表示阶数，每个元素表示每个方向上的元素的个数|
| dtype | 给出来了底层数据的类型（浮点数、复数、整数等）|
| strides | 此属性指定了读取数据的顺序。它可以对内存中的数据进行灵活的解释，形成数组视图|



```python

A = array([1,2,3],[3,4,5])
A.shape # (2, 3)
A.shape[0]  # 0
A.dtype # dtype('int64')
A.strides # (24, 8)

```

# 6.访问数组
通过索引来访问数组
## 6.1 数组切片
<br>数组的切片与列表类似。

 + M[i, :]是M的第i行的向量（张量）
 + M[ : , j] 是M的第j列的向量（张量）
 + M[2 : 4 , :]是在行2:4上的切片
 + M[2 :4 , 1 : 4] 是行和列的切片
 
 **注意：数组的切片是数组的视图。**
 
```python
M =  np.array([0,1,2,3],
           [4,5,6,7],
           [8,9,10,11])
#以下切片的形状和维数是多少
M[:2,1:-1]  #
M[1,:]     #
M[1,1]     #
M[1:2,:]    #
M[1:2,1:2]  #
```
## 6.2 使用切片修改数组
<br>因为切片是数组的视图，修改视图即为修改数组。赋值的数组必须和切片形状一致。<br>
M[2, :] = np.array([1,2,3,4]) <br>
M[:, 1] = np.array([[11],[12],[13]])  #注意列赋值的方式

# 7.数组构造函数
数组构造函数如下表

|方法|形状|生成结果|
|----|----|----|
|zeros((n,m))|(n,m)|由零填充矩阵|
|ones((n,m))|(n,m)|由1填充矩阵|
|diag(v,k)|(n,n)|获取v的主对角线，k默认为0|
|random.rand(n,m)|(n,m)|由（0,1）上的正态分布随机数填充|
|full((n,m),value)|（n,m)|由value填充矩阵|
|identity(n)|(n,n)|单位矩阵|
|arange(n)|(n,)|前n个整数|
|linspace(a,b,n)|(n,)|将区间（a,b）平均分成n个点组成的向量|

# 8.访问和修改形状
## 8.1 访问形状
+ 可以使用shape函数
<br> 如 np.shape(M)。此函数除了可以用在数组上，还可以用在标量和列表上。
+ 可以使用数组的shape属性
<br> 如 M.shape

## 8.2 维数
使用ndim(M)函数，或数组的属性ndim，M.ndim。需要注意，M.ndim = len(M.shape)。
## 8.3 重塑
+ reshape重塑
<br>
reshape函数在<big>不复制</big> 数据的情况下给出了一个数组的新视图，得到新形状：

```python
v = np.array([0,1,2,3,4,5,6,7])
M = v.reshape(2,4)
M.shape #（2,4）
M[0,0] = 10  #v[0]为10
#可以使用-1的形状参数，让python来计算形状
M = v.reshape(2,-1)
M = v.reshape(-1,4)
M = v.reshape(3,-1)  #错误，无法转换

v1 = v.reshape(-1,1)  #重塑为包含一列的矩阵
v2 = v.reshape(1,-1)  #重塑为包含一行的矩阵
```

+ 转置<br>
矩阵B是矩阵A的转置，则$B_{i,j}=A_{j,i}$,在数学上记为$B = A^T$。
```python
A = np.ones((4,5))
B = A.T
print(B.shape)
```

# 9.叠加
使用函数concatenate((a1,a2,...), axis =0)，沿axis方向叠加矩阵a1,a2,...。axis = 0时，垂直叠加。axis=1时水平叠加。
<br>有几个快捷函数可以使用
+ hstack((v1,v2,...)):水平叠加矩阵v1,v2,...
+ vstack((v1,v2,...)):垂直叠加矩阵v1,v2,...

# 10.作用于数组的函数
numpy提供了一系列的函数，如三角函数、指数/对数函数、统计函数等函数，他们大都是作用与数组元素的函数。

+ 作用与数组元素的函数<br>
一些三角函数、指数/对数函数都是作用与数组元素的函数。如$B = e^A$

```python
A = np.ones((4,5))
B = np.exp(A) #对每个元素求指数
print(B.shape)
```
也可以自己编写通用的函数，但需要注意所有的运算都必须是作用与数组元素的，而不是标量的。

+ 作用与数组的函数
一些统计函数如max、min、sum等，如果不提供其他参数，则作用与整个数组。

```python
A = np.arange(8).reshape(2,-1)  #[[0 1 2 3]，[4 5 6 7]]
print(np.sum(A))      # 整个矩阵和28
print(np.sum(A,axis=0))  #垂直相加 [ 4  6  8 10]
print(np.sum(A,axis=1))  #水平相加 [ 6 22]
```
# 11.线性代数的其他概念
## 11.1 矩阵的行列式
求行列式的矩阵是方阵。计算法则之一：主对角线元素积之和减去副对角线元素积。一般记作$det(A)$或$|A|$。**行列式就是线性变换的放大率.**

```python
import scipy.linalg as sl
A = np.random.rand(5,5)
print(sl.det(A))
```
## 11.2 矩阵的逆矩阵
对于方阵A，如果存在矩阵B，有$BA=AB=I$，则称B为A的逆矩阵，A的逆矩阵记作$A^{-1}$。如果A的逆矩阵存在，则$A^{-1}=\frac{A^*}{|A|}$, $A*$为A的伴随矩阵（为A的每个元素的代数余子式构成的矩阵，$a_{ij}$的代数余子式是A中出去i行j列后剩余项的行列式）。逆矩阵存在的条件：$|A|$不为零。
<br>
例：
线性方程组求解： Ax=b， 如果A的逆矩阵存在，则$x = A^{-1}b$

```python
import scipy.linalg as sl
A = np.random.rand(5,5)
Ainv = sl.inv(A)
```
## 11.3 矩阵的伪逆
当矩阵A不是方阵时（维度为m*n），不存在逆矩阵。在某些情况下，需要使用类似逆矩阵性质的情形，比如神经网络中的感知机权重学习规则。记A的伪逆为$A+$。当m>n时，$A^+=(A^TA)^{-1}A^T$，当m<n时，$A^+=A^T(A^TA)^{-1}$

```python
import scipy.linalg as sl
A = np.random.rand(4,5)
Apinv = sl.pinv(A)
print(Apinv)
```
## 11.4 矩阵的特征值与特征向量
对于方阵A，存在标量$\lambda$满足$Az = \lambda z$，则$\lambda$称为A的特征值，满足此式的向量$z$称为特征向量。<br>
特征值和特征向量表达了一个线性变换的特征。求特征向量，就是把矩阵A所代表的空间进行正交分解，使得A的向量集合可以表示为每个向量a在各个特征向量上的投影长度。我们通常求特征值和特征向量即为求出这个矩阵能使哪些向量只发生拉伸，而方向不发生变化，观察其发生拉伸的程度。<br>
$$(A - \lambda I) z = 0   \quad   （1）$$ 
+ 求特征值：<br>
根据$|A-\lambda I|=0$求得$\lambda$
+ 求特征向量 <br>
将求的$\lambda$带入(1)式，求得解即为特征向量。
+ 正定矩阵<br>(在性能优化时候比较有用，用在神经网络等求最优解的情况下)
 + 如果求得的所有特征值$\lambda$都大于0，则矩阵A为正定矩阵。对于正定矩阵A，对于非零向量有$x^TAx>0$。<br>
 + 如果特征值中有零存在，且其他特征值为正数，则A为半正定。对于正定矩阵A，对于非零向量有$x^TAx\ge0$。<br>
+ 特征值存在0，则A的逆矩阵不存在。如果特征值都不为0，则逆矩阵存在。

```python
import scipy.linalg as sl
A = np.random.rand(5,5)
eigval, eigvec = sl.eig(A)
print(eigval)
print(eigvec)
```

# 12. 数组其他特性
## 12.1 数组的复制
数组的切片是数组的视图，对切片的修改就是对原数组的修改。有时需要数组的或部分数组的副本，则需要考虑数组的复制。
+ 使用array函数生成副本
<br>可以使用array函数由视图生成一个数组。
```python
M = np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
M3 =np.array(M[1:3,1:]) 
M3[0]=100
print(M)
```

## 12.2 数组的关系逻辑运算
### 12.2.1 数组的比较
两个数组不能直接比较，比如
```python
A = np.array([0.1,0.])
B = np.array([0.,0.1])
if np.abs(B-A) < 1e-10: #引发异常
    print("equal")
```

对两个数组进行比较，则生成一个布尔数组。

```python
R1 = A > B
#生成一个布尔数组R1 [True False]
R2 = A < 0
#生成一个布尔数组R2 [False False]
```
### 12.2.2 数组的逻辑运算
对于两个布尔数组，可以使用逻辑运算：&， |， ~， 分别表示与、或、非。他们都是对应元素运算。
### 12.2.3 布尔数组索引
+ 一维数组索引<br>
可以使用布尔数组所谓索引，切片获得对应位置为True的部分数组元素。

```python
B = np.array([[True, False],
          [False,True]])
M = np.array([[2,3],
          [4,5]])
print(M[B])
#输出结果为[2,5]

data = np.linspace(1,100,100) #数据
deviation = np.random.normal(size=100) #偏差
exc1= data[(deviation<-0.5)|(deviation >0.5)] 
small = data[(abs(deviation)<0.1) & (data <5.)]
print(exc1)
print(small)

```
在模式分类的某些情况下，把运算结果中0.5以上的认为是1，小于0.5的认为是0，形成2分类的结果。请你随机生成10个0~1之间的数组，并把它转化为0,1的数组。


```python
a = np.random.rand(10)
#你的代码

```

+ 二维数组索引<br>
可以使用一维布尔数组作为索引，切片二维数组的行。

```python
arr = np.arragen(28).reshape(7,-1)
booling = np.array([True,False,False,True,True,False,False])
slice = arr[booling1]
print(slice)
#输出为
#[[ 0  1  2  3]
# [12 13 14 15]
# [16 17 18 19]]

arr1 = np.arange(7)
slice2 = arr[arr1>4]
print(slice2)
#输出是什么？
print(arr[arr1 <4 ,1:3])
#输出又是什么？
```
问题：如何使用布尔数组索引，对矩阵的列进行切片？即想取符合某些条件的列。

### 12.2.4 where命令
where命令将布尔数组作为条件，并范围满足条件的数组元素的索引，或者根据布尔数组中的值返回不同值。类似C/Java中的？：表达式
<br> where(condition, a,b)
<br>condition数组对应位置为true，则该位置返回a，否则返回b
<br>
将上一节中二分类结果数组的转化，可以简化为：


```python
a = np.where(a>0.5,1,0)
```

## 12.3 数组的广播
在两个数组进行运算时，如果他们大小不一致，但可兼容，则较小长度的数组可以进行广播扩展后，在进行运算。广播通常是在矩阵和向量进行算术运算时产生。
<br>可广播的条件（兼容）：矩阵M和向量s
+ s加到M的每一行上。当s的长度和M的列数一致时，s自动扩展成每一行都是s元素的矩阵S，S的行数和M一致，在进行算术运算。即可以直接使用M+s 。
+ s加到M的每一列上。当s的长度和M的行数一致时，则需手动将s重塑s.reshape(-1,1)，进行算术运算时自动进行列扩展后再相加。如 M + s.reshape(-1,1)。

```python
x = np.array([1,1,1,1])
z = np.array([-1,-1])
y = np.array([[1,2,3,4],[5,6,7,8]])
print(y+x)
print(y+z.reshape(-1,1))
```
## 12.4 其他函数
+ 排序 sort(a[,axis,kind,order])
+ argmax(a[,axis,out]),某个方向上最大值的索引
+ argmin(a[,axis,out])

## 课堂实例

### 矩阵运算：使用Numpy/Scipy进行线性代数问题求解
+ 求解线性方程组的解
+ 求矩阵的行列式、逆矩阵
+ 求解矩阵的特征值和特征向量
+ 

### 数据处理
有一北京2010~2015的pm25数据文件（BeijingPM20100101_20151231.csv），请统计重污染（>150）,中度污染（>75）,轻度污染(>35),良好(>0)等四种不同程度污染所占时间比例。<br>
+ （1）读入数据。可以用python的open函数及csv文件的读写方式读入到一个二维列表(a方式)，也可以使用numpy提供的loadtxt函数读入，直接获得numpy数组(b方式)。我们只需要文件中的1,2,6,7,8列（从0开始计数）。
 + a方式。读的过程中可以将一行读成一个列表，并同时把数据转换成整数。同时在读的过程中过滤数据，6,7,8行是'NA’的可以丢弃，或者设置为0。使用append函数，把每一行的列表作为numpy数组的一行附加上去。
 + b方式。可以整体一次性的把文件读入到numpy数组。如a =np.loadtxt('./BeijingPM20100101_20151231.csv',delimiter=',',dtype='str',skiprows=1,usecols=(1,2,6,7,8))。再进行数据清洗，需要使用到布尔索引切片，数据类型转换等。
+ （2）统计。该文件中的数据有是北京三个地点的数据记录（'四环','四环东','农展馆'），需要统计这三个地点总共的四种污染所占时间比例，精确到小数点后1位。。需要用到numpy的sum函数。
+ （3）统计三个地点每个月的平均pm值，精确到小数后一位。（较繁琐）

In [1]:
a = [x+1 for x in range(10)]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
import numpy as np
print(np.arange(12).reshape(3,4)+1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
import numpy as np
v1 = np.array([1.,2.,3.,4.]) 
v2 = np.array([5.,6.,7.,8.]) 
v = np.outer(v1,v2)
print(v.ndim)

2


In [16]:
import numpy as np
M = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
M[:,-1] = np.array([[1],[2],[3]])
print(M)

ValueError: could not broadcast input array from shape (3,1) into shape (3)

In [18]:
x = np.array([10 for x in range(15)]).reshape(5,3)
print(x)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]


In [21]:
y = np.ones((5,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
A = np.arange(12).reshape((3,-1))
print(A)
M = np.array(A[1:3,1:])
M[0] = 100
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
A = np.array([0.1,0.])
B = np.array([0.,0.1])
print(np.allclose(A,B))

False


In [30]:
A = np.arange(12)
np.random.shuffle(A)
B=np.where(A%2==1,0,A)
print(B)

[10  8  0  0  4  0  6  0  0  0  0  2]


In [33]:
A = np.array([3,2,6,9,1,22,12,99,1092,0,-1])
print(np.max(A))

1092


In [35]:
X = np.arange(15).reshape((3,5))
y = np.argmin(X, axis =0)
print(y)

[0 0 0 0 0]
